### ISSUE TITLE
Test problem, can not load the module.

### ISSUE THREAD

**Issue by JieFeng-cse** [epic-kitchens/action-models#6]
Sorry to bother again,
I want to use the pretrained weights in the TRN-pytorch project by Bolei [Zhou,](https://github.com/metalbubble/TRN-pytorch)  directly, but it fails.

**My bash is like that:**
```bash
$ python test_video.py --arch BNInception --dataset EPIC --modality RGB --weights pretrain/TRN_arch=BNInception_modality=RGB_segments=8-a770bfbd.pth.tar --frame_folder sample_data/frames_cut --consensus_type TRN
```
**To load the module, according to your code, I use:**

```python
net = TSN(num_class,
          args.test_segments,
          args.modality,
          base_model=args.arch,
          consensus_type=args.consensus_type,
          img_feature_dim=args.img_feature_dim, print_spec=False)

checkpoint = torch.load(args.weights)

net.load_state_dict(checkpoint['state_dict'])
net.cuda().eval()
```
**And the traceback is:**

```
Missing key(s) in state_dict: "consensus.classifier.1.weight", "consensus.classifier.1.bias", "consensus.classifier.3.weight", "consensus.classifier.3.bias". 
	Unexpected key(s) in state_dict: "consensus.pre_classifier.1.weight", "consensus.pre_classifier.1.bias", "consensus.classifiers.0.weight", "consensus.classifiers.0.bias", "consensus.classifiers.1.weight", "consensus.classifiers.1.bias".
```

Can you help me out? I want to use this to predict actions in kitchen which will be used to build an ontology for robot.

**Comment by willprice** [comment]
Hi @aplumpcslearner,

That's because the weights provided by the original TRN-pytorch project are trained for something-something/jester/charades. This means the output layers `consensus.classifier.*.(weight|bias)` aren't going to have the right shapes. On top of this we actually use a slightly different classifier architecture using 2 FC layers per classification head, one for nouns and one for verbs. You can load partial weights using `model.load_state_dict(checkpoint['state_dict'], strict=False)`. This will load all the weights that have compatible names and shapes into the model and return a named tuple containing the name of extra keys in the checkpoint and those missing in the checkpoint but needed for the model.
